### Data Pre Processing
There are several categorical columns **BUT** the model only understand numbers so we have to convert them to numbers. <br> 
But we cannot let them randomly be 1,2,3 because model might make a pattern like 3>2>1 and be confused. <br><br>
When there is a clear ranking given in categorical columns, we use **Ordinal Encoding**: giving straight numerical values to categorical columns(like Savings and Checking Account in our dataset where a heirarchy is provided) and we are assuming that "No account" field which we add will be lowest in the order. <br><br>
But since, in our dataset there is no clear ranking and spacing, we would be using **One Hot Encoding:** creating a new column for each categorical value and then give 0/1 based on existing/not existing.<br><br>

In [1]:
import pandas as pd 
import numpy as np

In [2]:
df = pd.read_csv('data.csv')

In [ ]:
# dropping unnamed column which is at index 0
df.drop(columns = ['Unnamed: 0'], inplace = True) # see only columns so no axis needed
df.drop(df.columns[0], axis = 1, inplace = True) 
'''extracting a raw value df.columns[0] and pandas need an axis 
to look for it'''

In [ ]:
# dropping the target column
X = df.drop(columns = ['Risk'])
Y = df['Risk']

In [ ]:
Y = Y.map({'bad': 1, 'good': 0}) # map instead of ordinal encoding because we decide which is 1 and which is 0

In [11]:
# Fill missing values
X["Saving accounts"] = X["Saving accounts"].fillna("No Account")
X["Checking account"] = X["Checking account"].fillna("No Account")

In [14]:
X.head()

,Age,Sex,Job,Housing,Saving accounts,Checking account,Credit amount,Duration,Purpose
0,67,male,2,own,No Account,little,1169,6,radio/TV
1,22,female,2,own,little,moderate,5951,48,radio/TV
2,49,male,1,own,little,No Account,2096,12,education
3,45,male,2,free,little,little,7882,42,furniture/equipment
4,53,male,2,free,little,little,4870,24,car

There are shortcuts for preprocessing like pd.get_dummies(df) but we would create a proper pipeline using ColumnTransfer and Pipeline

In [29]:
dff = pd.get_dummies(X) # this is a shortcut for one hot encoding
dff.head(1)

,Age,Job,Credit amount,Duration,Sex_female,Sex_male,Housing_free,Housing_own,Housing_rent,Saving accounts_No Account,...,Checking account_moderate,Checking account_rich,Purpose_business,Purpose_car,Purpose_domestic appliances,Purpose_education,Purpose_furniture/equipment,Purpose_radio/TV,Purpose_repairs,Purpose_vacation/others
0,67,2,1169,6,False,True,False,True,False,True,...,False,False,False,False,False,False,False,True,False,False

**Now there is one more column left to talk about, Job, which is surprisingly numerical.**<br><br>
**Check what values job holds, comes out to be 0,1,2,3 which COULD possibly be another sequence like 0=unskilled, 1=semi-skilled and so on.** <br><br>
**This means, job column is by default ordinal encoded, IT IS A GUESS NOT A CONCRETE DATA ATTRIBUTE**

In [34]:
'''value counts give the frequency of each value
sort_index sorts the output based on the value rather than frequency.'''
X["Job"].value_counts().sort_index()

Job
0     22
1    200
2    630
3    148
Name: count, dtype: int64

In [27]:
df["Job"].value_counts().sort_index()

Job
0     22
1    200
2    630
3    148
Name: count, dtype: int64